using System;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Windows.Input;

namespace DataGridAIFilterSample
{
    /// <summary>
    /// ViewModel for managing employees and applying AI-powered or local filtering in a .NET MAUI DataGrid.
    /// Implements MVVM pattern with data binding, commands, and filter logic.
    /// </summary>
    public class EmployeesViewModel : BindableObject
    {
        private readonly IAIFilterService _ai;

        /// <summary>
        /// Gets the collection of employees displayed in the DataGrid.
        /// </summary>
        public ObservableCollection<Employee> Employees { get; } =
            new(EmployeeRepository.GetEmployees());

        private string _prompt = "";

        /// <summary>
        /// Gets or sets the manual filter prompt entered by the user.
        /// </summary>
        public string Prompt
        {
            get => _prompt;
            set { if (_prompt == value) return; _prompt = value; OnPropertyChanged(); }
        }

        /// <summary>
        /// Gets a collection of predefined prompt suggestions for quick filtering.
        /// </summary>
        public ObservableCollection<string> PromptSuggestions { get; } = new()
        {
            "Employees with rating >= 8 and salary > 5000",
            "Show only Female employees born before 1990",
            "Name contains 'Tom' or Title contains 'Supervisor'",
            "BirthDate between 01/01/1980 and 12/31/1989",
            "Salary between 3000 and 4000",
            "Gender in [Male, Female] and Rating > 5",
            "EmployeeId between 1005 and 1015"
        };

        private string? _selectedSuggestion;

        /// <summary>
        /// Gets or sets the currently selected suggestion from the list.
        /// Updates <see cref="Prompt"/> when changed.
        /// </summary>
        public string? SelectedSuggestion
        {
            get => _selectedSuggestion;
            set
            {
                if (_selectedSuggestion == value) return;
                _selectedSuggestion = value;
                OnPropertyChanged();
                if (!string.IsNullOrWhiteSpace(value))
                    Prompt = value;
            }
        }

        /// <summary>
        /// Gets the current filter plan generated by AI or local parsing.
        /// </summary>
        public FilterPlan? CurrentPlan { get; private set; }

        /// <summary>
        /// Command to execute filtering based on the current prompt or selected suggestion.
        /// </summary>
        public ICommand ExecutePromptCommand { get; }

        /// <summary>
        /// Command to reset all filters and clear the prompt.
        /// </summary>
        public ICommand ResetCommand { get; }

        /// <summary>
        /// Event raised when the filter changes (used to refresh the DataGrid).
        /// </summary>
        public event EventHandler? FilterChanged;

        /// <summary>
        /// Initializes a new instance of the <see cref="EmployeesViewModel"/> class.
        /// </summary>
        /// <param name="ai">The AI filter service used to generate filter plans.</param>
        public EmployeesViewModel(IAIFilterService ai)
        {
            _ai = ai;
            ExecutePromptCommand = new Command(async () => await ExecuteAsync());
            ResetCommand = new Command(() =>
            {
                CurrentPlan = null;
                SelectedSuggestion = null;
                Prompt = string.Empty;
                FilterChanged?.Invoke(this, EventArgs.Empty);
            });
        }

        /// <summary>
        /// Executes the filtering logic by sending the prompt to the AI service or local parser.
        /// Updates <see cref="CurrentPlan"/> and raises <see cref="FilterChanged"/>.
        /// </summary>
        private async Task ExecuteAsync()
        {
            var toRun = !string.IsNullOrWhiteSpace(Prompt) ? Prompt : (SelectedSuggestion ?? string.Empty);
            toRun = toRun.Trim();

            if (string.IsNullOrWhiteSpace(toRun))
            {
                CurrentPlan = null;
                FilterChanged?.Invoke(this, EventArgs.Empty);
                return;
            }

            CurrentPlan = await _ai.CreateFilterPlanAsync(toRun);
            FilterChanged?.Invoke(this, EventArgs.Empty);
        }

        /// <summary>
        /// Builds a predicate function based on the current filter plan for use in DataGrid filtering.
        /// </summary>
        /// <returns>A predicate that evaluates whether a row matches the filter plan, or null if no plan exists.</returns>
        public Predicate<object>? BuildPredicate()
        {
            if (CurrentPlan is null)
            {
                return null;
            }

            return rowObj => EvalPlan(CurrentPlan, (Employee)rowObj);
        }

        /// <summary>
        /// Evaluates a filter plan against a single employee record.
        /// </summary>
        /// <param name="plan">The filter plan to evaluate.</param>
        /// <param name="employee">The employee record.</param>
        /// <returns><condition>true</condition> if the employee matches the filter; otherwise, <condition>false</condition>.</returns>
        private static bool EvalPlan(FilterPlan plan, Employee employee)
        {
            bool Combine(bool a, bool b, string logic) =>
                logic.Equals("or", StringComparison.OrdinalIgnoreCase) ? a || b : a && b;
            bool result = false;
            bool first = true;

            foreach (var node in plan.conditions)
            {
                bool local = false;
                if (node.group != null)
                {
                    local = EvalPlan(node.group, employee);
                }
                else if (node.condition != null)
                {
                    local = EvalCondition(node.condition, employee);
                }

                result = first ? local : Combine(result, local, plan.logic);
                first = false;
            }

            return result;
        }

        /// <summary>
        /// Evaluates a single filter condition against an <see cref="Employee"/> record.
        /// </summary>
        /// <param name="condition">
        /// The condition to evaluate, including field name, operator, and value(stringComparer).
        /// </param>
        /// <param name="employee">
        /// The employee record to test against the condition.
        /// </param>
        private static bool EvalCondition(Condition condition, Employee employee)
        {
            string normalizedOperator = (condition.operate ?? string.Empty).Trim().ToLowerInvariant() switch
            {
                // Equality
                "eq" => "equals",
                "equals" => "equals",
                "ne" => "notEquals",
                "notequals" => "notEquals",

                // Numeric/date comparisons
                "gt" => "greaterThan",
                "greaterthan" => "greaterThan",
                "gte" => "greaterThanOrEqual",
                "greaterthanorequal" => "greaterThanOrEqual",
                "lt" => "lessThan",
                "lessthan" => "lessThan",
                "lte" => "lessThanOrEqual",
                "lessthanorequal" => "lessThanOrEqual",

                // Date helpers
                "before" => "before",
                "after" => "after",

                // String operations
                "contains" => "contains",
                "startswith" => "startsWith",
                "endswith" => "endsWith",

                // Range & membership
                "between" => "between",
                "in" => "in",

                _ => "unknown"
            };

            object? leftHandValue = condition.field switch
            {
                "EmployeeId" => employee.EmployeeId,
                "Name" => employee.Name,
                "Title" => employee.Title,
                "Rating" => employee.Rating,
                "BirthDate" => employee.BirthDate,
                "Gender" => employee.Gender,
                "Salary" => employee.Salary,
                _ => null
            };

            if (leftHandValue is null)
            {
                return false;
            }

            (string? str, decimal? dec, int? integer, DateTime? date) ParseSingleValue(string? raw)
            {
                if (raw is null)
                {
                    return (null, null, null, null);
                }

                if (DateTime.TryParse(raw, out var parsedDate))
                {
                    return (raw, null, null, parsedDate);
                }

                if (int.TryParse(raw, out var parsedInt))
                {
                    return (raw, null, parsedInt, null);
                }

                if (decimal.TryParse(raw, out var parsedDecimal))
                {
                    return (raw, parsedDecimal, null, null);
                }

                return (raw, null, null, null);
            }

            bool StringCompare(Func<string, bool> predicate) =>
                leftHandValue is string stringValue && predicate(stringValue);

            bool NumberCompare(Func<decimal, bool> predicate) =>
                (leftHandValue is int intValue && predicate(intValue)) ||
                (leftHandValue is decimal decValue && predicate(decValue));

            bool DateCompare(Func<DateTime, bool> predicate) =>
                leftHandValue is DateTime dateValue && predicate(dateValue);

            var (stringValue, decimalValue, intValue, dateValue) = ParseSingleValue(condition.value);

            return normalizedOperator switch
            {
                // equals / notEquals
                "equals" => leftHandValue switch
                {
                    string => StringCompare(s => string.Equals(s, stringValue, StringComparison.OrdinalIgnoreCase)),
                    int or decimal => NumberCompare(n => n == (intValue ?? decimalValue ?? 0)),
                    DateTime => DateCompare(d => dateValue.HasValue && d.Date == dateValue.Value.Date),
                    _ => false
                },

                "notEquals" => leftHandValue switch
                {
                    string => StringCompare(stringComparer => !string.Equals(stringComparer, stringValue, StringComparison.OrdinalIgnoreCase)),
                    int or decimal => NumberCompare(n => n != (intValue ?? decimalValue ?? 0)),
                    DateTime => DateCompare(d => !dateValue.HasValue || d.Date != dateValue.Value.Date),
                    _ => false
                },

                // numbers and dates
                "greaterThan" => NumberCompare(numberComparer => numberComparer > (intValue ?? decimalValue ?? 0)) ||
                                           DateCompare(d => dateValue.HasValue && d > dateValue.Value),

                "greaterThanOrEqual" => NumberCompare(numberComparer => numberComparer >= (intValue ?? decimalValue ?? 0)) ||
                                           DateCompare(d => dateValue.HasValue && d >= dateValue.Value),

                "lessThan" => NumberCompare(numberComparer => numberComparer < (intValue ?? decimalValue ?? 0)) ||
                                           DateCompare(d => dateValue.HasValue && d < dateValue.Value),

                "lessThanOrEqual" => NumberCompare(numberComparer => numberComparer <= (intValue ?? decimalValue ?? 0)) ||
                                           DateCompare(d => dateValue.HasValue && d <= dateValue.Value),

                "before" => DateCompare(date => dateValue.HasValue && date < dateValue.Value),
                "after" => DateCompare(date => dateValue.HasValue && date > dateValue.Value),

                // strings
                "contains" => StringCompare(stringComparer => stringComparer.Contains(stringValue ?? string.Empty, StringComparison.OrdinalIgnoreCase)),
                "startsWith" => StringCompare(stringComparer => stringComparer.StartsWith(stringValue ?? string.Empty, StringComparison.OrdinalIgnoreCase)),
                "endsWith" => StringCompare(stringComparer => stringComparer.EndsWith(stringValue ?? string.Empty, StringComparison.OrdinalIgnoreCase)),

                // ranges and membership
                "between" => (condition.values?.Count ?? 0) >= 2 && (
                    leftHandValue is DateTime dVal &&
                    DateTime.TryParse(condition.values![0], out var startDate) &&
                    DateTime.TryParse(condition.values![1], out var endDate) &&
                    dVal >= startDate && dVal <= endDate

                    || leftHandValue is int iVal &&
                    int.TryParse(condition.values![0], out var startInt) &&
                    int.TryParse(condition.values![1], out var endInt) &&
                    iVal >= startInt && iVal <= endInt

                    || leftHandValue is decimal mVal &&
                    decimal.TryParse(condition.values![0], out var startMoney) &&
                    decimal.TryParse(condition.values![1], out var endMoney) &&
                    mVal >= startMoney && mVal <= endMoney
                ),

                "in" => condition.values != null && (leftHandValue switch
                {
                    string sVal => condition.values.Any(value => string.Equals(value, sVal, StringComparison.OrdinalIgnoreCase)),
                    int iVal => condition.values.Any(value => int.TryParse(value, out var parsed) && parsed == iVal),
                    decimal mVal => condition.values.Any(value => decimal.TryParse(value, out var parsed) && parsed == mVal),
                    object value => false
                }),

                object value => false
            };
        }
    }
}